package com.litong.modules.opencv.engine.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("mail_receiver", "id", MailReceiver.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("t_cron4j_task_info", "id", Cron4jTaskInfo.class);
		arp.addMapping("t_db_connect_info", "id", DbConnectInfo.class);
		arp.addMapping("t_log_db_connected", "id", LogDbConnected.class);
		arp.addMapping("t_log_mail_send", "id", LogMailSend.class);
	}
}

