package com.litong.modules.opencv.engine.common.model;

import com.litong.modules.opencv.engine.common.model.base.BaseCron4jTaskInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cron4jTaskInfo extends BaseCron4jTaskInfo<Cron4jTaskInfo> {
	
}
