package com.litong.modules.opencv.engine.common.model;

import com.litong.modules.opencv.engine.common.model.base.BaseDbConnectInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbConnectInfo extends BaseDbConnectInfo<DbConnectInfo> {
	
}
