package com.litong.modules.opencv.engine.common.model;

import com.litong.modules.opencv.engine.common.model.base.BaseLogDbConnected;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogDbConnected extends BaseLogDbConnected<LogDbConnected> {
	
}
