package com.litong.modules.opencv.engine.common.model;

import com.litong.modules.opencv.engine.common.model.base.BaseLogMailSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogMailSend extends BaseLogMailSend<LogMailSend> {
	
}
