package com.litong.modules.opencv.engine.common.model;

import com.litong.modules.opencv.engine.common.model.base.BaseMailReceiver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MailReceiver extends BaseMailReceiver<MailReceiver> {
	
}
