package com.litong.modules.opencv.engine.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDbConnectInfo<M extends BaseDbConnectInfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 数据库地址
	 */
	public void setJdbcUrl(java.lang.String jdbcUrl) {
		set("jdbc_url", jdbcUrl);
	}
	
	/**
	 * 数据库地址
	 */
	public java.lang.String getJdbcUrl() {
		return getStr("jdbc_url");
	}
	
	/**
	 * 用户名
	 */
	public void setJdbcUser(java.lang.String jdbcUser) {
		set("jdbc_user", jdbcUser);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getJdbcUser() {
		return getStr("jdbc_user");
	}
	
	/**
	 * 密码
	 */
	public void setJdbcPswd(java.lang.String jdbcPswd) {
		set("jdbc_pswd", jdbcPswd);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getJdbcPswd() {
		return getStr("jdbc_pswd");
	}
	
	/**
	 * 状态 0关闭,1开启
	 */
	public void setStatus(java.lang.Long status) {
		set("status", status);
	}
	
	/**
	 * 状态 0关闭,1开启
	 */
	public java.lang.Long getStatus() {
		return getLong("status");
	}
	
	/**
	 * 是否删除,1删除,0未删除
	 */
	public void setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 是否删除,1删除,0未删除
	 */
	public java.lang.String getIsDel() {
		return getStr("is_del");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}
