package com.litong.modules.opencv.engine.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogMailSend<M extends BaseLogMailSend<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 收件人
	 */
	public void setTo(java.lang.String to) {
		set("to", to);
	}
	
	/**
	 * 收件人
	 */
	public java.lang.String getTo() {
		return getStr("to");
	}
	
	/**
	 * 主题
	 */
	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}
	
	/**
	 * 主题
	 */
	public java.lang.String getSubject() {
		return getStr("subject");
	}
	
	/**
	 * 邮件内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 邮件内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 是否删除,1删除,0未删除
	 */
	public void setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 是否删除,1删除,0未删除
	 */
	public java.lang.String getIsDel() {
		return getStr("is_del");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}
