package com.litong.modules.opencv.engine.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCron4jTaskInfo<M extends BaseCron4jTaskInfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 任务信息
	 */
	public void setTaskDesc(java.lang.String taskDesc) {
		set("task_desc", taskDesc);
	}
	
	/**
	 * 任务信息
	 */
	public java.lang.String getTaskDesc() {
		return getStr("task_desc");
	}
	
	/**
	 * 任务模式
	 */
	public void setTaskMode(java.lang.String taskMode) {
		set("task_mode", taskMode);
	}
	
	/**
	 * 任务模式
	 */
	public java.lang.String getTaskMode() {
		return getStr("task_mode");
	}
	
	/**
	 * 表达式
	 */
	public void setCron(java.lang.String cron) {
		set("cron", cron);
	}
	
	/**
	 * 表达式
	 */
	public java.lang.String getCron() {
		return getStr("cron");
	}
	
	/**
	 * 负责人
	 */
	public void setCharge(java.lang.String charge) {
		set("charge", charge);
	}
	
	/**
	 * 负责人
	 */
	public java.lang.String getCharge() {
		return getStr("charge");
	}
	
	/**
	 * 类名
	 */
	public void setClassName(java.lang.String className) {
		set("class_name", className);
	}
	
	/**
	 * 类名
	 */
	public java.lang.String getClassName() {
		return getStr("class_name");
	}
	
	/**
	 * 是否开启
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}
	
	/**
	 * 是否开启
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}
	
	/**
	 * 是否删除,1删除,0未删除
	 */
	public void setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 是否删除,1删除,0未删除
	 */
	public java.lang.String getIsDel() {
		return getStr("is_del");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}
