package com.litong.modules.monitoring.db.common.model;

import com.litong.modules.monitoring.db.common.model.base.BaseCron4jTaskInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cron4jTaskInfo extends BaseCron4jTaskInfo<Cron4jTaskInfo> {
	
}
