package com.litong.modules.monitoring.db.common.model;

import com.litong.modules.monitoring.db.common.model.base.BaseDbConnectInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbConnectInfo extends BaseDbConnectInfo<DbConnectInfo> {
	
}
