package com.litong.modules.monitoring.db.common.model;

import com.litong.modules.monitoring.db.common.model.base.BaseLogMailSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogMailSend extends BaseLogMailSend<LogMailSend> {
	
}
