package com.litong.modules.monitoring.db.common.model;

import com.litong.modules.monitoring.db.common.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	
}
